### ISSUE TITLE
Add additional e-mails

### ISSUE THREAD

**Issue by spaceraccoon** [YaleSTC/vesta#316]
* [x] any accepted membership changes to groups (#414)
* [x] group locking / finalizing (#414)
* [x] manually triggered e-mails to all relevant students in each draw (once per draw) (#415)
  * [x] intent reminders
  * [x] group locking reminders
* [x] your turn to select a suite? (in #343)

**Comment by esoterik** [comment]
done!
